import React,{useState} from "react";
import {PortalLayout,Heading,Tag,Button,Stats,Card,Banner} from "../components";
const nav=["Visão geral","Minha escala","Trocas de plantão","Justificar falta","Alertas","Histórico"];
const user={initials:"HC",name:"Dra. Helena Costa",subtitle:"Clínica Geral • CRM-SC 12345"};
export function ProfessionalPortal({navigate}){
 const [active,setActive]=useState("Visão geral"); const [notice,setNotice]=useState("");
 const navTo=x=>{setActive(x);if(x==="Trocas de plantão")navigate("/profissional/troca");else if(x==="Justificar falta")navigate("/profissional/falta");else if(x==="Minha escala")navigate("/profissional/escala");else if(x!=="Visão geral")setNotice(x+" selecionado.")};
 return <PortalLayout role="Clínica Médica" user={user} items={nav} active={active} onNav={navTo}><Heading title="Bom dia, Dra. Helena" subtitle="Sua jornada está organizada e sem conflitos para os próximos 7 dias." action="Ver minha escala" onAction={()=>navigate("/profissional/escala")}/><Banner title="Jornada em conformidade">36 h trabalhadas nos últimos 7 dias • 12 h de descanso antes do próximo plantão • nenhum conflito entre instituições.</Banner><section className="next-shift"><div className="shift-id"><div className="calendar-icon">▣</div><div><small>Próximo plantão</small><h3>Hoje, 19h–07h • Clínica Médica</h3><p>Hospital Santo Antônio • Setor 3A</p></div></div><div className="shift-actions"><Tag tone="positive">Confirmado</Tag><Button variant="neutral" onClick={()=>navigate("/profissional/troca")}>Solicitar troca</Button></div></section><Stats items={[{value:"36 h",label:"Horas nos últimos 7 dias"},{value:"12 h",label:"Descanso antes do próximo"},{value:"0",label:"Conflitos de jornada"},{value:"4",label:"Instituições vinculadas"}]}/><section className="nearby"><div className="section-heading"><div><h2>Ações rápidas</h2></div><Tag tone="positive">IA disponível</Tag></div><div className="three-cards"><Card title="Solicitar troca" body="Encontre profissionais compatíveis para seu plantão."><Button onClick={()=>navigate("/profissional/troca")}>Começar</Button></Card><Card title="Justificar falta" body="Envie informações e documentos para registro e validação."><Button onClick={()=>navigate("/profissional/falta")}>Justificar</Button></Card><Card title="Ver escala" body="Consulte os próximos plantões por setor e instituição."><Button onClick={()=>navigate("/profissional/escala")}>Abrir escala</Button></Card></div></section>{notice&&<div className="toast" onClick={()=>setNotice("")}>{notice}</div>}</PortalLayout>
}
